const actionConst = {
    SIGNIN: "SIGNIN",
    SIGNIN_PROCESS: "SIGNIN_PROCESS",
    SIGNIN_PROCESS_DONE: "SIGNIN_PROCESS_DONE",
    SIGNIN_FAILED: "SIGNIN_FAILED",
    RESET_SIGNIN_FAILED: "RESET_SIGNIN_FAILED",
    SIGNOUT_PROCESS: "SIGNOUT_PROCESS",
    SIGNOUT: "SIGNOUT",
    SIGNUP: "SIGNUP",
    SIGNUP_CREATE: "SIGNUP_CREATE",
    SIGNUP_CANCEL: "SIGNUP_CANCEL",
    SIGNUP_CREATED: "SIGNUP_CREATE",
}
export default actionConst;