const actionConst = {
    SIGNIN: "SIGNIN",
    SIGNIN_PROCESS: "SIGNIN_PROCESS",
    SIGNIN_PROCESS_DONE: "SIGNIN_PROCESS_DONE",
    SIGNIN_FAILED: "SIGNIN_FAILED",
    RESET_SIGNIN_FAILED: "RESET_SIGNIN_FAILED",
    SIGNOUT_PROCESS: "SIGNOUT_PROCESS",
    SIGNOUT: "SIGNOUT",
    SIGNUP: "SIGNUP",
    SIGNUP_CREATE: "SIGNUP_CREATE",
    SIGNUP_CANCEL: "SIGNUP_CANCEL",
    SIGNUP_CREATED: "SIGNUP_CREATE",
    USER_MENU_SELECT: "USER_MENU_SELECT",
    SHOW_ADD_ITEM: "SHOW_ADD_ITEM",
    SHOW_ADD_ITEM_CANCEL: "SHOW_ADD_ITEM_CANCEL",
    ADD_ITEM_CREATE: "ADD_ITEM_CREATE",
    ADD_ITEM_CREATED: "ADD_ITEM_CREATED",
    ITEM_LISTS_FETCH: "ITEM_LISTS_FETCH",
    ITEM_LISTS_FETCHED: "ITEM_LISTS_FETCHED",
    ITEM_LISTS_DELETING: "ITEM_LISTS_DELETING",
    ITEM_LISTS_DELETED: "ITEM_LISTS_DELETED",

}
export default actionConst;